### ISSUE TITLE
Issue with cms-urls when not running Bloomreach experience locally

### ISSUE THREAD

**Issue by TimoWestland** [bloomreach/experience-react-sdk#1]
I'm currently using the bloomreach SDK for our React frontend.

I would like to use the `getApiUrl` function as shown in the examples. This uses the `updateCmsUrls` method from: https://github.com/bloomreach/experience-react-sdk/blob/master/src/utils/cms-urls.js 

This probably works fine when bloomreach is running locally on my machine, but I need it to go to `http://www.grandvision.test.onehippo.com/resourceapi`. This won't work because the `:` is hardcoded in the cms-urls.js file. This should be changed to only be added to the cmsUrls.baseUrl when a port is specified.

**Comment by robbertkauffman** [comment]
Hi Timo,

Thanks for reporting! Sounds like a good improvement. In the mean time, you could set cmsPort to '80'. Let me know if that doesn't work.

Best,
Robbert

**Comment by TimoWestland** [comment]
Hi Robbert,

Thanks for your reply. Setting the port to 80 results in `http://grandvision.test.onehippo.com:80/site/resourceapi`, so it doesn't resolve this issue.

**Comment by robbertkauffman** [comment]
Why wouldn't that work? 80 is the default port. For example, if I request http://www.google.com:80 or https://www.google.com:443 for https it works.

**Comment by TimoWestland** [comment]
You are right, the port was not the issue. The issue here is that it goes to `/site/resourceapi` where i need it to go to just `/resourceapi`. I don't see a way to override the `cmsContextPath` with an empty string so not sure how I can achieve that using the `getApiUrl` method.

I will close #2 because it doesn't solve the issue.

**Comment by robbertkauffman** [comment]
Got it. I'll commit a fix that allows you to provide an empty contextPath.

**Comment by robbertkauffman** [comment]
Added support for empty context-path and port: https://github.com/bloomreach/experience-react-sdk/commit/13d57d014e4bb6eefc9800b482ef0785207b6a63

**Comment by TimoWestland** [comment]
Awesome, thanks!
