### ISSUE TITLE
Unsafe object equation check on props.request in CMS page

### ISSUE THREAD

**Issue by TimoWestland** [bloomreach/experience-react-sdk#12]
The react SDK has an unsafe check in `page.js`. The CmsPage component does has the following `componentDidUpdate` code:

```javascript
componentDidUpdate (prevProps, prevState) {
  if (this.props.request !== prevProps.request) {
    const parsedUrl = this.parseRequest(this.props.request);
    this.fetchPageModel(parsedUrl.path, parsedUrl.preview);
  }
}
```

This is checking two objects for equality, which is leading to unexpected results. We only ran into this issue now because for us this is only causing issues in Safari when the browser back/forward buttons are used. Since we are using the server-sided setup and the `componentDidUpdate` method only gets called client-sided. 

I've sym-linked the SDK locally into our site and added these logs in the comopnentDidUpdate method: 

```javascript
console.log('next: ', this.props.request) 
console.log('prev: ', prevProps.request)
console.log(this.props.request !== prevProps.request)
```

In the logs below you can see that the two objects that are compared are identical, but is still resulting in an unexpected `true`:

<img width="457" alt="screenshot 2018-10-10 17 48 06" src="https://user-images.githubusercontent.com/3959082/46749621-6bd47500-ccb6-11e8-9bde-20e1b2b90310.png">

This is causing the re-fetching of the update and a complete re-render of the site because React.Context is being used at the top level of the component tree. I've created an pr: #11 with a fix for this. 

Why is this causing issues for us?
We currently "abuse" the pageModel prop on the CmsPage to pass additional data to our CmsContainer components, because we currently have no other way to do this:

```javascript
return (
    <CmsPage
      cmsUrls={cmsUrls}
      pageModel={{ ...pageModel, labels, request }}
      request={request}
      createLink={createLink}
      componentDefinitions={componentDefinitions}
    >
      {() => (
        <Layout pageModel={pageModel} asPath={asPath} isSolaris={isSolaris} preview={preview}>
          <RenderCmsComponent />
        </Layout>
      )}
    </CmsPage>
)
```

This is why our page broke in safari using the back button, `pageModel.labels` were not defined anymore because the SDK caused an unexpected re-fetch op de pageModel and updated it's internal state with it, which got passed to the container components, and didn't include the data we added earlier anymore. Server-sided renders always went well because this only passed the pageModel trough the constructor of CmsPage and thus contained our added data.

Having an option to do something like this:

```javascript
  <RenderCmsComponent additionalProps={{ labels, request }} />
```

Would also be a really nice addition, so we don't have to abuse the pageModel props. But adding the safer check is quite urgent for us as its a blocking issue for our go-live.

**Comment by robbertkauffman** [comment]
Hi @TimoWestland ,

Thanks for the pull request. Just merged it to develop and cut a new beta release (0.4.5-rc1). I did some testing in Safari and it looks good on my end. Let me know if this fixes your issue.

Regarding the props issue: if I pass all props from RenderCmsComponent to the component that RenderCmsComponent renders (e.g. <ExampleComponent {...this.props}/>, would that fix it for you?

Best,
Robbert

**Comment by TimoWestland** [comment]
That was really fast, thank you! I will test it right away 👍 

About the props, that would be perfect! Although I do think you need to find a way to pass it all the way down to here in `container-item.js` then:

```javascript
        const componentEl = 
          React.createElement(componentDefinitions[component.label].component,
          { configuration: component, pageModel: pageModel, preview: preview,
            componentDefinitions: componentDefinitions}, null);
        return (componentEl);
```

But if you can do that, that would be awesome :)

Thanks!

**Comment by TimoWestland** [comment]
Hi @robbertkauffman,

The fix works like a charm! I've created an separate issue for the component props issue: #14, so this thread can be closed.

Thanks again for your quick response!
