### ISSUE TITLE
Have a way to pass trough custom props to RenderCmsComponent

### ISSUE THREAD

**Issue by TimoWestland** [bloomreach/experience-react-sdk#14]
As discussed in #12, it would be really nice to have a way to pass trough props to RenderCmsComponent like so:

```javascript
  <RenderCmsComponent labels={labels} request={request} />
```

And then have them spread onto the component that gets rendered in `container-item.js`

For example:
```javascript
  <Example component {...this.props} />
```

**Comment by dokmic** [comment]
Hey @TimoWestland,

We will not be able to implement this feature because this library is under the maintenance stage at the moment, and we can only do security and bug fixes.

I would recommend using Higher-Order Components or React Context to work this problem around.
