### ISSUE TITLE
Add additional exports of components and utils

### ISSUE THREAD

**Issue by TimoWestland** [bloomreach/experience-react-sdk#3]
During my project implementation with this SDK, I ran into the issue of not having access some utils and components. I think they can be exported because it doesn't add any risk and just can be ignored if the are not needed by implementation.

**Comment by robbertkauffman** [comment]
Hi @TimoWestland ,

Can you close this if the static-components branch 4df7eb6b794532b9123239b1ef3d088c00299b09 fixes your issue?

Thanks!

Robbert

**Comment by TimoWestland** [comment]
For sure, i'll close #4  as well :)
