### ISSUE TITLE
How to retrieve an image url from a custom Image Set?

### ISSUE THREAD

**Issue by LovisaSkeppeTrustly** [bloomreach/experience-react-sdk#34]
Hi!

I am trying to add Gallery Manager to our CMS. However I am having trouble getting the urls for each entry in the image set. Is there a helper function like `getImageUrl` that I can use?

Example Image Set of a specific image:
```
"uee735ad096fd439db7ada6fb5ff87f78": {
  "id": "ee735ad0-96fd-439d-b7ad-a6fb5ff87f78",
  "_links": {
     "site": {
       "href": "/site/binaries/content/gallery/namespace/test-images/hero4_original.jpg",
       "type": "resource"
      }
  },
  "name": "hero4_original.jpg",
  "displayName": "hero4_original.jpg",
  "tablet": {
    "width": 768,
    "height": 512,
    "length": 190311,
    "mimeType": "image/jpeg",
    "lastModified": 1570181774263,
    "versionedNode": false,
    "_links": {
         "site": {
             "href": "/site/binaries/content/gallery/namespace/test- 
 images/hero4_original.jpg/hero4_original.jpg/namespace%3Atablet",
             "type": "resource"
         }
     }
  },
  "fileName": "hero4_original.jpg",
  "original": {
   ...
  },
  "thumbnail": {
  ...
  },
  "versionedNode": false
},
```

**Comment by PetroPavlenko** [comment]
How about adding image component ?

**Comment by LovisaSkeppeTrustly** [comment]
@PetroPavlenko Can you please elaborate? is that a component you provide? how else can a custom made component magically parse a json structure?

**Comment by LovisaSkeppeTrustly** [comment]
Right now I can use your `getImageUrl` function like this:

```
import {getImageUrl} from 'bloomreach-experience-react-sdk';

getImageUrl(reference, pageModel, preview)
```

I will then get the following based on the response I pasted in the question:
```
"hostConfigStuff + /site/binaries/content/gallery/namespace/test-images/hero4_original.jpg" <- getImageUrl(
   {$ref: "/content/uee735ad096fd439db7ada6fb5ff87f78"},
   pageModel,
   preview
)
```

Do you have a function something like this: `getImageUrl(reference, `**_variant_**`, pageModel, preview)`
So I can simply do this in my code:
```
"hostConfigStuff + /site/binaries/content/gallery/namespace/test- 
 images/hero4_original.jpg/hero4_original.jpg/namespace%3Atablet" <- getImageUrl(
   {$ref: "/content/uee735ad096fd439db7ada6fb5ff87f78"},
   'tablet'
   pageModel,
   preview
)
```

**Comment by dokmic** [comment]
Hey @LovisaSkeppeTrustly,

I've just checked `getImageUrl` implementation, and we do have such functionality.
Here is the function [signature](https://github.com/bloomreach/experience-react-sdk/blob/master/packages/sdk/src/utils/image-url.js#L21):
```javascript
getImageUrl(imageRef, pageModel, preview, variant);
```

In your case, you can try to do that like:
```javascript
getImageUrl(
   {$ref: "/content/uee735ad096fd439db7ada6fb5ff87f78"},
   pageModel,
   preview,
   'tablet',
);
```

Let me know if it answers your question.

**Comment by LovisaSkeppeTrustly** [comment]
OMG thanks a bunch! @dokmic I'll close this
